# XLA_PYTHON_CLIENT_PREALLOCATE=false uv run train_finetuning.py --utd_ratio=2 --start_training 5000                 --max_steps 500000                 --config=configs/rlpd_config.py                 --config.backup_entropy=False                 --config.hidden_dims="(512,512)"                 --config.num_min_qs=2  --config.num_qs=2 --log_dir /home/elias/Masterstudium/DeepLearningRobotics/rlpd/logs/state/run2/checkpoints --name Reward1

# XLA_PYTHON_CLIENT_PREALLOCATE=false uv run train_finetuning.py --utd_ratio=2 --start_training 5000                 --max_steps 500000                 --config=configs/rlpd_config.py                 --config.backup_entropy=False                 --config.hidden_dims="(512,512)"                 --config.num_min_qs=2  --config.num_qs=2 --log_dir /home/elias/Masterstudium/DeepLearningRobotics/rlpd/logs/state/run3/checkpoints --name Reward1 --seed 1

# XLA_PYTHON_CLIENT_PREALLOCATE=false uv run train_finetuning.py --utd_ratio=2 --start_training 5000                 --max_steps 500000                 --config=configs/rlpd_config.py                 --config.backup_entropy=False                 --config.hidden_dims="(512,512)"                 --config.num_min_qs=2  --config.num_qs=2 --log_dir /home/elias/Masterstudium/DeepLearningRobotics/rlpd/logs/state/run4/checkpoints --name Reward1 --seed 2

# XLA_PYTHON_CLIENT_PREALLOCATE=false uv run train_finetuning.py --utd_ratio=2 --start_training 5000                 --max_steps 500000                 --config=configs/rlpd_config.py                 --config.backup_entropy=False                 --config.hidden_dims="(512,512)"                 --config.num_min_qs=2  --config.num_qs=2 --log_dir /home/elias/Masterstudium/DeepLearningRobotics/rlpd/logs/state/run5/checkpoints --name Reward1 --seed 3

# XLA_PYTHON_CLIENT_PREALLOCATE=false uv run train_finetuning.py --utd_ratio=2 --start_training 5000                 --max_steps 500000                 --config=configs/rlpd_config.py                 --config.backup_entropy=False                 --config.hidden_dims="(512,512,512,512)"                 --config.num_min_qs=2  --config.num_qs=2 --log_dir /home/elias/Masterstudium/DeepLearningRobotics/rlpd/logs/state/run6/checkpoints --name Reward1 --seed 4

# XLA_PYTHON_CLIENT_PREALLOCATE=false uv run train_finetuning.py --utd_ratio=2 --start_training 5000                 --max_steps 500000                 --config=configs/rlpd_config.py                 --config.backup_entropy=False                 --config.hidden_dims="(1024,1024)"                 --config.num_min_qs=2  --config.num_qs=2 --log_dir /home/elias/Masterstudium/DeepLearningRobotics/rlpd/logs/state/run7/checkpoints --name Reward1 --seed 5

# XLA_PYTHON_CLIENT_PREALLOCATE=false uv run train_finetuning.py --utd_ratio=2 --start_training 5000                 --max_steps 500000                 --config=configs/rlpd_config.py                 --config.backup_entropy=False                 --config.hidden_dims="(512,512)"                 --config.num_min_qs=2  --config.num_qs=2 --log_dir /home/elias/Masterstudium/DeepLearningRobotics/rlpd/logs/state/run8/checkpoints --name Reward3 --agxreward 3 --seed 0

# XLA_PYTHON_CLIENT_PREALLOCATE=false uv run train_finetuning.py --utd_ratio=2 --start_training 5000                 --max_steps 500000                 --config=configs/rlpd_config.py                 --config.backup_entropy=False                 --config.hidden_dims="(512,512)"                 --config.num_min_qs=2  --config.num_qs=2 --log_dir /home/elias/Masterstudium/DeepLearningRobotics/rlpd/logs/state/run9/checkpoints --name Reward3 --agxreward 3 --seed 1

# XLA_PYTHON_CLIENT_PREALLOCATE=false uv run train_finetuning.py --utd_ratio=2 --start_training 5000                 --max_steps 500000                 --config=configs/rlpd_config.py                 --config.backup_entropy=False                 --config.hidden_dims="(512,512)"                 --config.num_min_qs=2  --config.num_qs=2 --log_dir /home/elias/Masterstudium/DeepLearningRobotics/rlpd/logs/state/run10/checkpoints --name Reward3 --agxreward 3 --seed 2

XLA_PYTHON_CLIENT_PREALLOCATE=false uv run train_finetuning.py --utd_ratio=2 --start_training 5000                 --max_steps 500000                 --config=configs/rlpd_config.py                 --config.backup_entropy=False                 --config.hidden_dims="(512,512)"                 --config.num_min_qs=2  --config.num_qs=2 --log_dir /home/elias/Masterstudium/DeepLearningRobotics/rlpd/logs/state/run11/checkpoints --name Reward5 --agxreward 5 --seed 0

# XLA_PYTHON_CLIENT_PREALLOCATE=false uv run train_finetuning.py --utd_ratio=2 --start_training 5000                 --max_steps 500000                 --config=configs/rlpd_config.py                 --config.backup_entropy=False                 --config.hidden_dims="(512,512)"                 --config.num_min_qs=2  --config.num_qs=2 --log_dir /home/elias/Masterstudium/DeepLearningRobotics/rlpd/logs/state/run10/checkpoints --name Reward1 --agxreward 3 --seed 1

# XLA_PYTHON_CLIENT_PREALLOCATE=false uv run train_finetuning.py --utd_ratio=2 --start_training 5000                 --max_steps 500000                 --config=configs/rlpd_config.py                 --config.backup_entropy=False                 --config.hidden_dims="(512,512)"                 --config.num_min_qs=2  --config.num_qs=2 --log_dir /home/elias/Masterstudium/DeepLearningRobotics/rlpd/logs/state/run10/checkpoints --name Reward1 --agxreward 3 --seed 2
